return {
    "tpope/vim-surround",

    -- ┌─────────────────────────────────────────────────────────────┐
    -- │                         vim-surround                        │
    -- ├─────────────────────────────────────────────────────────────┤
    -- │ Add surroundings:                                           │
    -- │   ys{motion}{char}   Surround motion/text object            │
    -- │   yss{char}          Surround current line                  │
    -- │   yS{motion}{char}   Surround + put on separate lines       │
    -- │   ySS{char}          Surround line + put on separate lines  │
    -- │                                                             │
    -- │ Change surroundings:                                        │
    -- │   cs{old}{new}       Change existing surrounding            │
    -- │   cS{old}{new}       Change + put on separate lines         │
    -- │                                                             │
    -- │ Delete surroundings:                                        │
    -- │   ds{char}           Delete existing surrounding            │
    -- │                                                             │
    -- │ Visual mode:                                                │
    -- │   S{char}            Surround visual selection              │
    -- │   gS{char}           Surround selection on separate lines   │
    -- └─────────────────────────────────────────────────────────────┘

    -- Examples:
    --
    --   ysiw)       word → (word)
    --   ysiw]       word → [word]
    --   ysiw}       word → {word}
    --   ysiw"       word → "word"
    --
    --   yss)        entire line → (entire line)
    --   ySS}        entire line → multiline { ... }
    --
    --   cs"'        "hello" → 'hello'
    --   cs])        [hello] → (hello)
    --   cst<p>      <div>hello</div> → <p>hello</p>
    --
    --   ds"         remove "..."
    --   ds)         remove (...)
    --   dst         remove HTML/XML tags
    --
    --   viwS)       visual selection → (selection)
    --
    -- Surround targets:
    --   ( ) { } [ ] < >     brackets / parentheses
    --   ' " `               quotes
    --   t                   HTML/XML tag
    --   b                   alias for )
    --   B                   alias for }
    --   r                   alias for ]
    --   a                   alias for >
    --   w                   word
    --   W                   WORD
    --   s                   sentence
    --   p                   paragraph
    --
    -- Note:
    --   Opening brackets add surrounding spaces:
    --       ysiw(  → ( word )
    --       ysiw)  → (word)
    --
    -- Full documentation:
    --   :help surround
    --   https://github.com/tpope/vim-surround/blob/master/doc/surround.txt
}
